repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.1
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-annotations==2.9.0",
        "flake8-black==0.3.3",
        "flake8-docstrings==1.6.0",
        #"flake8-isort==4.1.2",  # flake8-isort doesn't support flake8 5 yet, uncomment this when it does.
        "flake8-variables-names==0.0.5"
      ]
