name: Build buttercup.pyz and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-create: true
    - name: Install Env
      # shiv will download the dependencies it needs on its own
      run: |
        pip install --upgrade pip
        pip install shiv
        pip install poetry
        pip install poetry2setup
    - name: Add CURRENT_TIME env property
      run: echo "CURRENT_TIME_VERSION=v$(date '+%s')" >> $GITHUB_ENV
    - name: Build the sucker
      run: |
        sed -i -e "s/?????/${{ env.CURRENT_TIME_VERSION }}/g" buttercup/__init__.py
        make build
    - name: Remove source to make sure it doesn't interfere with the tests
      run: rm -rf buttercup/
    - name: Run selfcheck on compiled binary
      run: ./build/buttercup.pyz selfcheck
