name: Static Code Analysis

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: Install latest pyflakes and pycodestyle version
      run: |
        pip install --upgrade pip
        pip install flake8 pyflakes pycodestyle
    - name: Run Static Analysis
      run: |
        /usr/bin/git diff -u ${{ github.event.pull_request.base.sha }} | poetry run flake8 --diff
