name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.x"
    - uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
    - name: Install Dependencies
      run: |
        poetry install -v
    - name: Run Tests
      run: |
        poetry run pytest --cov=buttercup
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: poetry run coveralls --service=github
